---
ansible_user: aaa
ansible_pass: L@bd0g!!
ansible_ssh_pass: L@bd0g!!
ansible_become_pass: L@bd0g!!

# Integration with NetBox
netbox_token: 0123456789abcdef0123456789abcdef01234567

# Day zero credentials for Cumulus Linux
cumulus:
    user: cumulus
    pass: CumulusLinux!

# Day zero credentials for Cisco IOS XR
cisco:
    user: cisco
    pass: cisco

# Day zero credentials for Arista EOS
arista:
    user: aaa
    pass: aaa

# SNMP credentials for all devices
all_snmp:
    user: Collector
    pass:
        auth: SUPER_AUTH
        encr: SUPER_PASS
...
