---
# General vars
working_folder: /tmp/network_fabric

# Netbox integration
netbox_host: localhost
netbox_frontend_container: netboxdocker_nginx_1

# Some fabric parameters:
bgp:
    password: DC_F@BR!C$
    send: 10
    receive: 30

# Defaults for Docker containers
docker:
    path_to_containers: containers
    repo: akarneliuk

# Domain name (perhaps, should be moved to NetBox)
domain_name: de.karnet.com
...
