---
# General vars
working_folder: /tmp/network_fabric

# Netbox integration
netbox_host: localhost
netbox_frontend_container: netboxdocker_nginx_1

# Some fabric parameters:
bgp:
    password: DC_F@BR!C$
    send: 10
    receive: 30
...
