---
- name: CONTAINER WITH {{ container_item }} // CREATING FOLDER 
  file:
      dest: "{{ docker.path_to_containers }}/{{ container_item }}"
      state: directory
  tags:
      - infra_enabler_install

- name: CONTAINER WITH {{ container_item }} // GETTING IP OF INFLUXDB
  docker_container:
      name: dcf_influxdb
  become: yes
  register: dcf_influxdb_inspect
  tags:
      - infra_enabler_install

- name: CONTAINER WITH {{ container_item }} // TEMPLATING TELEGRAF CONFIG
  template:
      src: "{{ container_item }}_template.j2"
      dest: "{{ docker.path_to_containers }}/{{ container_item }}/telegraf.conf"
  tags:
      - infra_enabler_install

- name: CONTAINER WITH {{ container_item }} // LAUNCHING CONTAINER
  docker_container:
      name: dcf_telegraf_syslog
      image: telegraf
      state: started
      command: "-config /etc/telegraf/telegraf.conf"
      networks:
          - name: "{{ docker.private_network.name }}"
      purge_networks: yes
      ports:
          - "514:514/udp"
      volumes:
           - "{{ pwd_actual }}/{{ docker.path_to_containers }}/{{ container_item }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
  become: yes
  tags:
      - infra_enabler_install
      - infra_enabler_ops
...
