---
- name: CREATING FOLDER FOR ALL CONTAINERS
  file:
      dest: "{{ docker.path_to_containers }}"
      state: directory
  tags:
      - infra_enabler_install

- name: GETTING PWD
  command: pwd
  register: pwd
  tags:
      - infra_enabler_install
      - infra_enabler_ops

- name: SETTING PWD VARIABLE
  set_fact:
      pwd_actual: "{{ pwd.stdout }}"
  tags:
      - infra_enabler_install
      - infra_enabler_ops

- name: STARTING COLLECTION LOOP ...
  include_tasks: collection_loop.yml
  tags:
      - infra_enabler_install
      - infra_enabler_ops

- name: CREATING USER-DEFINED DOCKER NETWORK
  shell: "docker network create {{ docker.private_network.name }} {% if docker.private_network.ipv6 %}--ipv6{% endif %} {% if docker.private_network.subnet is defined %}--subnet {{ docker.private_network.subnet }}{% endif %} {% if docker.private_network.gateway is defined %}--gateway {{ docker.private_network.gateway }}{% endif %}"
  ignore_errors: yes
  become: yes
  tags:
      - infra_enabler_install
      - infra_enabler_ops

- name: BUILDING CONTAINERS ...
  include_tasks: "container_{{ container_item }}.yml"
  loop:
      - dcf_influxdb
      - dcf_telegraf_syslog
      - dcf_telegraf_snmp
      - dcf_grafana
      - dcf_dhcp
      - dcf_dns
      - dcf_ftp
      - dcf_http
  loop_control:
      loop_var: container_item
  tags:
      - infra_enabler_install
      - infra_enabler_ops
...
